<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.10"/>
    
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0.187"/>
    <xacro:property name="wheel_offset_z" value="0.04"/>
    
    <xacro:property name="caster_wheel_radius" value="0.030"/>
    <xacro:property name="caster_wheel_mass" value="0.05"/>
    <xacro:property name="caster_wheel_offset_x" value="0.16"/>
    <xacro:property name="caster_wheel_offset_z" value="-${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <!-- base link-->
    <link name="base_link">
    </link>
    <!-- base link-->


    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>



    <xacro:include filename="body_components/chassis.xacro" />
    <xacro:include filename="body_components/supports.xacro" />
    <xacro:include filename="body_components/wheels.xacro" />
    

    
</robot>